# frozen_string_literal: true

namespace :manifest do
  task display: :environment do
    puts Stimulus::Manifest.generate_from(Rails.root.join('app/javascript/controllers'))
  end

  task update: :environment do
    manifest =
      Stimulus::Manifest.generate_from(Rails.root.join('app/javascript/controllers'))

    File.open(Rails.root.join('app/javascript/controllers/index.js'), 'w+') do |index|
      index.puts '// This file is auto-generated by ./bin/rails stimulus:manifest:update'
      index.puts '// Run that command whenever you add a new controller or create them with'
      index.puts '// ./bin/rails generate stimulus controllerName'
      index.puts
      index.puts %(import { application } from "./application")
      index.puts manifest
    end
  end
end
